import type { NextPage } from 'next'
import Head from 'next/head'
import Square from '../components/square'
import styled from 'styled-components';
import Triangle from '../components/triangle';
import Circle from '../components/circle';
import Grid from '../components/grid';
import Link from 'next/link';
import { useEffect } from 'react';

const WrapExposition = styled.main`
  display: flex;
  justify-content: center;
  align-items: center;
  background: black;
  padding: 2rem;
`;

const variants = {
  hidden: { opacity: 0, x: -200, y: 0 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: 0, y: -100 },
}

const Grids: NextPage = () => {
  return (
    <div>
      <Head>
        <title>2D Maps Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapExposition>
        <div className="menu">
          <nav>
            <ul>
              <li><Link href="/">Home</Link></li>
              <li><Link href="grids">Grids</Link></li>
              <li><Link href="grids/editor">Editor</Link></li>
              <li><Link href="grids/editor-full">Editor (Full)</Link></li>
              <li><Link href="grids/play">Play</Link></li>
              <li><Link href="grids/play-full">Play (Full)</Link></li>
            </ul>
          </nav>
        </div>
        <Grid className="pixel-grid" columns="5" size="50">

          <Square/>
          <Triangle orientationH="right" rectangle={true}/>
          <Circle orientationH="right" orientationV="down" corner={true}/>
          <Triangle orientationH="left" orientationV="top"/>

          <Triangle orientationH="right" orientationV="down"/>
          <Triangle orientationH="left" orientationV="down"/>
          <Square rombo={true}/>
          <Triangle orientationH="right" orientationV="top"/>

          <Circle/>
          <Circle orientationH="right" orientationV="top" corner={true}/>
          <Circle orientationH="left" orientationV="down" corner={true}/>
          <Circle orientationH="left" orientationV="top" corner={true}/>

          <Circle orientationH="left" center={true}/>
          <Circle orientationV="top" center={true}/>
          <Circle orientationV="down" center={true}/>
          <Circle orientationH="right" center={true}/>
          
          <Triangle orientationH="left" rectangle={true}/>
          <Triangle orientationV="top" rectangle={true}/>
          <Triangle orientationV="down" rectangle={true}/>
          <Square/>

        </Grid>
      </WrapExposition>

      <footer>
        
      </footer>
    </div>
  )
}

export default Grids
