import type { NextPage } from 'next'
import Head from 'next/head'
import Square from '../components/square'
import styled from 'styled-components';
import Triangle from '../components/triangle';
import Circle from '../components/circle';
import Link from 'next/link';
import Grid from '../components/grid';
const WrapExposition = styled.main`
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: black;
  padding: 2rem;
  overflow: hidden;
  html,body{
    overflow: hidden;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>2D Maps Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WrapExposition>
        <div className="menu">
          <nav>
            <ul>
              <li><Link href="/"><a>Home</a></Link></li>
              <li><Link href="grids"><a>Grids</a></Link></li>
            </ul>
          </nav>
        </div>
        <Grid columns="5" size="5">

          <Square/>
          <Triangle orientationH="right" rectangle={true}/>
          <Circle orientationH="right" orientationV="down" corner={true}/>
          <Triangle orientationH="left" orientationV="top"/>

          <Triangle orientationH="right" orientationV="down"/>
          <Triangle orientationH="left" orientationV="down"/>
          <Square rombo={true}/>
          <Triangle orientationH="right" orientationV="top"/>

          <Circle/>
          <Circle orientationH="right" orientationV="top" corner={true}/>
          <Circle orientationH="left" orientationV="down" corner={true}/>
          <Circle orientationH="left" orientationV="top" corner={true}/>

          <Circle orientationH="left" center={true}/>
          <Circle orientationV="top" center={true}/>
          <Circle orientationV="down" center={true}/>
          <Circle orientationH="right" center={true}/>
          
          <Triangle orientationH="left" rectangle={true}/>
          <Triangle orientationV="top" rectangle={true}/>
          <Triangle orientationV="down" rectangle={true}/>
          <Square/>

        </Grid>
      </WrapExposition>
        

      <footer>
        
      </footer>
    </div>
  )
}

export default Home
